# Generated by Django 4.0.4 on 2022-05-08 02:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='option_responses', to='exams.option'),
        ),
        migrations.AlterUniqueTogether(
            name='response',
            unique_together={('user', 'question')},
        ),
    ]
