# Generated by Django 4.0.4 on 2022-05-31 00:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0003_usersubjectdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubjectdetail',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_user_subject_list', to='exams.subject'),
        ),
        migrations.AlterField(
            model_name='usersubjectdetail',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_user_subject_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
